run:
  allow-parallel-runners: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - varnamelen
    - depguard
    - ireturn

linters-settings:
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - dupl
